### ISSUE TITLE
Prompt does not take my arguments

### ISSUE THREAD

**Issue by boisseleau** [sirap-group/generate-swap-project#126]
TypeError: in task "prompt": Cannot read property 'length' of undefined
    at askPromise.then.then.answers (/home/boisseleau/.nvm/versions/node/v8.11.2/lib/node_modules/generate-swap-project/dist/lib/tasks/prompt.js:97:30)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by rbecheras** [comment]
Please add complete log output (the command + the output before the error)

**Comment by boisseleau** [comment]
```sh
$ gen swap-project
[12:17:57] starting generate
[12:17:57] ✔ running tasks: [ 'swap-project' ]
[12:17:58] starting swap-project 
[12:17:58] starting swap-project:default task 
[12:17:58] starting swap-project:project task 
[12:17:58] starting swap-project 
[12:17:58] starting swap-project:prompt task 
? Project name ? my-swap-app
? Project directory ? my-swap-app
? Description ? my-swap-app SWAP app
? Git host platform ? 
? Author username ? boisseleau
? Author name ? boisseleau
TypeError: in task "prompt": Cannot read property 'length' of undefined
    at askPromise.then.then.answers (/home/boisseleau/.nvm/versions/node/v8.11.2/lib/node_modules       /generate-swap-project/dist/lib/tasks/prompt.js:97:30)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```
